# Generated by Django 5.0 on 2025-03-06 15:29

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0002_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='theory',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.subject'),
        ),
    ]
