# Generated by Django 5.0 on 2025-03-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0003_alter_theory_content_alter_theory_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
