# Generated by Django 5.0 on 2025-03-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0004_theory_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theory',
            name='video_url',
        ),
        migrations.AddField(
            model_name='theory',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
