# Generated by Django 5.0 on 2025-03-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0005_remove_theory_video_url_theory_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theory',
            name='video',
        ),
        migrations.AddField(
            model_name='theory',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
