# Generated by Django 5.1.6 on 2025-02-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_incorrectanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
    ]
