# Generated by Django 5.0 on 2025-02-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='incorrectanswer',
            name='duration',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
