# Generated by Django 5.0 on 2025-02-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_incorrectanswer_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incorrectanswer',
            name='duration',
        ),
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.IntegerField(default=60, help_text='Тривалість у хвилинах'),
        ),
    ]
