# Generated by Django 5.0 on 2025-02-20 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_remove_incorrectanswer_duration_test_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
