# Generated by Django 5.0 on 2025-02-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_testresult_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
