# Generated by Django 5.0 on 2025-02-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_testresult_is_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='is_completed',
        ),
    ]
