# Generated by Django 5.0 on 2025-02-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_phoneverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Учень'), ('teacher', 'Вчитель')], default='student', max_length=10),
        ),
    ]
