# Generated by Django 5.0 on 2025-04-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_classes', '0002_class_delete_myclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='class',
            name='section',
        ),
        migrations.AddField(
            model_name='class',
            name='class_number',
            field=models.CharField(default='Невідомо', max_length=200),
        ),
        migrations.AddField(
            model_name='class',
            name='student_name',
            field=models.CharField(default='Невідомо', max_length=200),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.CharField(default='Невідомо', max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.CharField(default='Невідомо', max_length=200),
        ),
    ]
