# Generated by Django 5.0 on 2025-04-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_classes', '0003_remove_class_audience_remove_class_class_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_number',
            new_name='class_name',
        ),
        migrations.RemoveField(
            model_name='class',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.AddField(
            model_name='class',
            name='audience',
            field=models.CharField(blank=True, default='Невідомо', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, default='Невідомо', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.CharField(blank=True, default='Невідомо', max_length=200, null=True),
        ),
    ]
