# Generated by Django 5.0 on 2025-04-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_classes', '0004_rename_class_number_class_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='audience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
