# Generated by Django 5.0 on 2025-04-14 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_classes', '0005_alter_class_audience_alter_class_class_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='audience',
            field=models.CharField(default='Default audience', max_length=255),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(default='Default audience', max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(default='Default audience', max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.CharField(default='Default audience', max_length=100),
        ),
    ]
