# Generated by Django 5.0 on 2025-04-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_classes', '0009_class_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
