# Generated by Django 5.0 on 2025-04-15 10:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_classes', '0013_assignmentsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='instructions',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
