# Generated by Django 5.0 on 2025-04-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_classes', '0014_remove_class_qr_code_assignment_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
