# Generated by Django 5.0 on 2025-04-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_classes', '0015_class_teacher_first_name_class_teacher_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='teacher_first_name',
            field=models.CharField(default='Default name', max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher_last_name',
            field=models.CharField(default='Default lastname', max_length=100),
        ),
    ]
