# Generated by Django 5.0 on 2025-04-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_classes', '0016_alter_class_teacher_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='teacher_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
