# Generated by Django 5.0 on 2025-04-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_classes', '0018_assignment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
