# Generated by Django 5.0 on 2025-04-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.AddField(
            model_name='course',
            name='course_format',
            field=models.TextField(default='Not provided', help_text='Список тем та план курсу'),
        ),
        migrations.AddField(
            model_name='course',
            name='learn_outcome',
            field=models.TextField(default='Теми, які будуть розглянуті на курсі.'),
        ),
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='course_photos/'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
