# Generated by Django 5.0 on 2025-04-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_created_at_course_course_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(default='Не має предмета', max_length=255),
        ),
    ]
