# Generated by Django 5.0 on 2025-04-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
    ]
