# Generated by Django 5.0 on 2025-02-24 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_teacher_age_post_teacher_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='teacher_age',
        ),
        migrations.RemoveField(
            model_name='post',
            name='teacher_experience',
        ),
        migrations.RemoveField(
            model_name='post',
            name='teacher_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='teacher_phone',
        ),
        migrations.RemoveField(
            model_name='post',
            name='teacher_photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='teacher_subjects',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='first_name',
            field=models.CharField(default="Ім'я невідоме", max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='post',
            name='last_name',
            field=models.CharField(default='Прізвище невідоме', max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AddField(
            model_name='post',
            name='preparation_levels',
            field=models.CharField(default='7-9 класи', max_length=255, verbose_name='Підготовка до класів'),
        ),
        migrations.AddField(
            model_name='post',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Вартість заняття (₴/год)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
