# Generated by Django 5.0 on 2025-02-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_post_description_remove_post_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='default_photo.jpg', upload_to='post_photos/', verbose_name='Фото профілю'),
        ),
    ]
