# Generated by Django 5.0 on 2025-02-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='about',
            field=models.TextField(blank=True, verbose_name='Про себе'),
        ),
        migrations.AddField(
            model_name='post',
            name='calendar',
            field=models.TextField(blank=True, verbose_name='Календар'),
        ),
        migrations.AddField(
            model_name='post',
            name='resume',
            field=models.TextField(blank=True, verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='post',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='post_photos/', verbose_name='Фото профілю'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preparation_levels',
            field=models.CharField(max_length=255, verbose_name='Підготовка до класів'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість заняття (₴/год)'),
        ),
    ]
