# Generated by Django 5.0 on 2025-02-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_post_resume_post_email_post_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subjects',
            field=models.CharField(default='', max_length=255, verbose_name='Предмети'),
        ),
    ]
