# Generated by Django 5.0 on 2025-02-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_post_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Предмет')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='subjects',
        ),
        migrations.AddField(
            model_name='post',
            name='subjects',
            field=models.ManyToManyField(to='home.subject', verbose_name='Предмети'),
        ),
    ]
