# Generated by Django 5.0 on 2025-02-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_subject_remove_post_subjects_post_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='post',
            name='subjects',
            field=models.CharField(default='', max_length=255, verbose_name='Предмети'),
        ),
    ]
