# Generated by Django 5.0 on 2025-04-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_profile_last_visit_profile_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_visit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
    ]
