# Generated by Django 5.1.6 on 2025-02-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVisit',
        ),
    ]
