# Generated by Django 5.1.6 on 2025-02-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
