# Generated by Django 5.1.6 on 2025-02-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_theory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theory',
        ),
    ]
