# Generated by Django 5.0 on 2025-02-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вік'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Локація (місто, область)'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефону'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_photos/', verbose_name='Фото профілю'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.CharField(blank=True, max_length=255, verbose_name='Предмети викладання'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teaching_mode',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Очно'), ('mixed', 'Змішано')], default='online', max_length=10, verbose_name='Формат навчання'),
        ),
    ]
