# Generated by Django 5.0 on 2025-02-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_teacher', '0002_teacherprofile_age_teacherprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва предмета')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subjects',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='profile_teacher.subject', verbose_name='Предмети викладання'),
        ),
    ]
