# Generated by Django 5.0 on 2025-02-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_teacher', '0003_subject_remove_teacherprofile_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.TextField(blank=True, verbose_name='Предмети викладання (перераховуйте через кому)'),
        ),
    ]
